'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var FETCH_RESOURCE = 'FETCH_RESOURCE';
exports.FETCH_RESOURCE = FETCH_RESOURCE;
var CREATE_RESOURCE = 'CREATE_RESOURCE';
exports.CREATE_RESOURCE = CREATE_RESOURCE;
var DESTROY_RESOURCE = 'DESTROY_RESOURCE';
exports.DESTROY_RESOURCE = DESTROY_RESOURCE;
var PATCH_RESOURCE = 'PATCH_RESOURCE';
exports.PATCH_RESOURCE = PATCH_RESOURCE;